version: "3"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8000"
    restart: always
    depends_on:
      - db

volumes:
  postgres_data: